user: "@{{ botaccount }}:{{ server_name }}"
server: "{{ server_name }}"
device_name: "{{ device_name }}"
access_token: "{{ access_token }}"
can_invite_the_bot: "{{ can_invite_the_bot }}"
can_be_invited_by_the_bot: "{{ can_be_invited_by_the_bot }}"
can_answer_to_the_bot: "{{ can_answer_to_the_bot }}"
bot_name: "{{ botname }}"
im_bridged: "{{ im_bridged }}"
welcome_message: "Hello, welcome"
lang: "{{ language }}"